apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
  namespace: vos-tool
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: efs-sc  # Use EFS for multi-pod access
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
  namespace: vos-tool
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc  # Use EFS for multi-pod access
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-utils
  fileSystemId: fs-xxxxxxxxx  # Replace with your EFS file system ID
  directoryPerms: "0755"
